[package]
name = "resolve"
version = "0.1.0"
edition = "2024"

[dependencies]
timing.workspace = true
serde = { version = "1.0.229", features = ["derive", "rc"] }
syntax = { path = "../syntax" }

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"

[dev-dependencies]
project = { path = "../project" }
