[package]
name = "ref-docs"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8"
clap = { version = "4.5.51", features = ["derive"] }
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
syntax = { path = "../../src/syntax" }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "signal"] }

[dev-dependencies]
tower = { version = "0.5", features = ["util"] }
