#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Invalid {
    WrongModuleArgumentCategory,
    ExpectedInductiveTypeForFieldProjection,
    InductiveTypeIsNotARecordType,
    RootOrMaterializedModuleCannotBePublishedAsAChild,
    ReflectedRecursiveProgramFieldIsNotStrictlyPositive,
    CannotGoBackParentAlreadyAtRootModule,
    ModuleParameterCannotBeAppliedWithParameters,
    UnsupportedExistsMultipleNamedBinders,
    UnsupportedExistsProofBinder,

    RequiresAProgramRecord,
    ConstructorBinderHeadMismatch,
    NonPositiveConstructorBinderTail,
    ConstructorHeadMismatch,
    NonPositiveConstructorTail,
    NonPositiveConstructor,
    ExpectedInductiveTypeInBaseOfAssociatedAccess,
    ExternalModuleWasNotResolved,
    InductionBinderTypeMustReduceToAnInductiveType,
    InductiveDeclarationMetadataWasNotFound,
    MatchScrutineeMustHaveAnInductiveType,
    MatchScrutineeTypeDoesNotMatchItsPath,
    ModuleInstantiationPathMustContainAtLeastOneModule,
    ProgramApplicationHeadHasTheWrongCategory,
    ProgramApplicationHeadIsNotAFunctionValueOrComputation,
    ProgramApplicationHeadValueIsNotAFunctionThunk,
    ProgramAssociatedItemOwnerMustBeAProgramTypeInThisModule,
    ProgramAssociatedItemOwnerMustBeInThisModule,
    ProgramAssociatedItemParametersMustHaveTypeVtype,
    ProgramAssociatedValuesDoNotTakeValueArguments,
    ProgramBlockSyntaxCannotBeElaboratedAsASetPropExpression,
    ProgramCaseBranchesAreNotInConstructorOrder,
    ProgramCaseMustHaveOneOrderedBranchPerConstructor,
    ProgramCasePathDoesNotNameAProgramDatatype,
    ProgramCaseScrutineeDatatypeDoesNotMatchItsPath,
    ProgramCaseScrutineeIsNotAProgramDatatypeValue,
    ImplicitFunctionValueApplication,
    ProgramConstructorPathDoesNotNameAProgramDatatype,
    ProgramDatatypeParametersMustHaveTypeVtype,
    ProgramFieldProjectionExpectsARecordValue,
    ProgramFunctionValuesRequireAnExplicitForceBeforeApplication,
    ProgramRecordProjectionIsNotAComputation,
    ProgramSyntaxCannotBeElaboratedAsASetPropExpression,
    ProgramTypeModuleParametersDoNotAcceptParameters,
    ProgramTypeVariableUsedAsAValue,
    ProgramTypeVariableUsedAsAnApplicationHead,
    ProgramTypeVariablesDoNotAcceptParameters,
    ProgramValueRequiresReflection,
    ProgramValueUsedAsAValueType,
    ReflectedDefinitionCannotBeAppliedWithParameters,
    SetReflectionRequiresAProgramDefinition,
    TokenMatchEscapedTemplateExpansion,
    VtypeIsOnlyValidInAProgramBinder,
    TakeCurrentlyExpectsExactlyOneNamedVariable,
    TakeMapMustHaveANonDependentCodomain,
    UnsupportedTakeProofBinder,
    AlreadyAtRootModule,
    AssociatedProgramItemHasTheWrongCategory,
    AssociatedItemIsNotAProgramComputation,
    AssociatedItemIsNotAProgramDefinition,
    AssociatedItemIsNotAProgramValue,
    BoundVariableOutsideSupportedContext,
    ProgramFunctionTypeNeedsAnnotation,
    CannotInferSquashTypeArgumentIsNotBoxedProgramCode,
    CheckpointSourceMissingFromProject,
    ChildModuleInDeclarationExecutionOrder,
    CyclicDefinitionDependency,
    CyclicModuleParameterType,
    DefinitionIsNotAProgramComputation,
    DefinitionIsNotAProgramValue,
    DefinitionLocalContextIsOutsideReferenceScope,
    DuplicateProgramAssociatedItemParameter,
    ExpectedProgramStructureTypeInRecordLiteral,
    ExpectedProgramTypeBeforeAssociatedAccess,
    ExpectedProgramTypeBeforeAssociatedApplication,
    ExpectedASetPropSort,
    ExpectedADefinitionReference,
    ExpectedASort,
    ExpectedAStructureDataType,
    ExpectedAStructureTypeInAStructureLiteral,
    ExpectedInductionBinders,
    ExpectedModuleParameter,
    ExpressionDoesNotHaveASort,
    FailedToInferAProductTypeForTakeMap,
    IncorrectProgramTypeSort,
    MissingDefinitionCaptures,
    NameDoesNotDenoteAProgramComputation,
    OnlyProgramDatatypesAcceptTypeParameters,
    OnlyProgramParametersSupportSetReflection,
    RecordConstructorHasTooFewFields,
    RecordFieldIndexOutOfBounds,
    RecordFieldsMustBeNonRecursive,
    ReflectionRequiresAProgramDefinition,
    SourceDefinitionWasNotResolved,
    UnexpandedMacroInHir,
    UnknownHirModule,
    UnknownHirModuleInExecutionOrder,
    UnknownHirParameter,
    UnknownDeclarationInExecutionOrder,
    UnknownDefinition,
    UnknownModuleExpressionScope,
    UnknownModuleParameter,
    UnresolvedDefinitionReflection,
    UnresolvedFrontendDeclaration,
    UnresolvedFrontendValueDeclaration,
    UnresolvedReflectionMetavariable,
    UnresolvedStructureMember,
}
impl std::fmt::Display for Invalid {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::WrongModuleArgumentCategory => f.write_str("module argument uses the wrong syntactic category"),
            Self::ExpectedInductiveTypeForFieldProjection => f.write_str("Expected inductive type for field projection"),
            Self::InductiveTypeIsNotARecordType => f.write_str("Inductive type is not a record type"),
            Self::RootOrMaterializedModuleCannotBePublishedAsAChild => f.write_str("Root or materialized module cannot be published as a child"),
            Self::ReflectedRecursiveProgramFieldIsNotStrictlyPositive => f.write_str("reflected recursive Program field is not strictly positive"),
            Self::CannotGoBackParentAlreadyAtRootModule => f.write_str("Cannot go back parent: already at root module"),
            Self::ModuleParameterCannotBeAppliedWithParameters => f.write_str("Module parameter cannot be applied with parameters"),
            Self::UnsupportedExistsMultipleNamedBinders => f.write_str("Elaboration of multiple named binds in Exists is not implemented"),
            Self::UnsupportedExistsProofBinder => f.write_str("Elaboration of named bind or subset with proof in Exists is not implemented"),

            Self::RequiresAProgramRecord => f.write_str("::#^ requires a Program record"),
            Self::ConstructorBinderHeadMismatch => f.write_str("Constructor binder type head does not match inductive type name"),
            Self::NonPositiveConstructorBinderTail => f.write_str("Constructor binder type tail contains inductive type name in non-strictly positive position"),
            Self::ConstructorHeadMismatch => f.write_str("Constructor type head does not match inductive type name"),
            Self::NonPositiveConstructorTail => f.write_str("Constructor type tail contains inductive type name in non-strictly positive position"),
            Self::NonPositiveConstructor => f.write_str("Constructor contains inductive type name in non-strictly positive position"),
            Self::ExpectedInductiveTypeInBaseOfAssociatedAccess => f.write_str("Expected inductive type in base of associated access"),
            Self::ExternalModuleWasNotResolved => f.write_str("External module was not resolved"),
            Self::InductionBinderTypeMustReduceToAnInductiveType => f.write_str("Induction binder type must reduce to an inductive type"),
            Self::InductiveDeclarationMetadataWasNotFound => f.write_str("Inductive declaration metadata was not found"),
            Self::MatchScrutineeMustHaveAnInductiveType => f.write_str("Match scrutinee must have an inductive type"),
            Self::MatchScrutineeTypeDoesNotMatchItsPath => f.write_str("Match scrutinee type does not match its path"),
            Self::ModuleInstantiationPathMustContainAtLeastOneModule => f.write_str("Module instantiation path must contain at least one module"),
            Self::ProgramApplicationHeadHasTheWrongCategory => f.write_str("Program application head has the wrong category"),
            Self::ProgramApplicationHeadIsNotAFunctionValueOrComputation => f.write_str("Program application head is not a function value or computation"),
            Self::ProgramApplicationHeadValueIsNotAFunctionThunk => f.write_str("Program application head value is not a function thunk"),
            Self::ProgramAssociatedItemOwnerMustBeAProgramTypeInThisModule => f.write_str("Program associated item owner must be a Program type in this module"),
            Self::ProgramAssociatedItemOwnerMustBeInThisModule => f.write_str("Program associated item owner must be in this module"),
            Self::ProgramAssociatedItemParametersMustHaveTypeVtype => f.write_str("Program associated item parameters must have type \\VType"),
            Self::ProgramAssociatedValuesDoNotTakeValueArguments => f.write_str("Program associated values do not take value arguments"),
            Self::ProgramBlockSyntaxCannotBeElaboratedAsASetPropExpression => f.write_str("Program block syntax cannot be elaborated as a Set/Prop expression"),
            Self::ProgramCaseBranchesAreNotInConstructorOrder => f.write_str("Program case branches are not in constructor order"),
            Self::ProgramCaseMustHaveOneOrderedBranchPerConstructor => f.write_str("Program case must have one ordered branch per constructor"),
            Self::ProgramCasePathDoesNotNameAProgramDatatype => f.write_str("Program case path does not name a Program datatype"),
            Self::ProgramCaseScrutineeDatatypeDoesNotMatchItsPath => f.write_str("Program case scrutinee datatype does not match its path"),
            Self::ProgramCaseScrutineeIsNotAProgramDatatypeValue => f.write_str("Program case scrutinee is not a Program datatype value"),
            Self::ImplicitFunctionValueApplication => f.write_str("Program computation returned a function value; use explicit \\bind and \\force before applying another argument"),
            Self::ProgramConstructorPathDoesNotNameAProgramDatatype => f.write_str("Program constructor path does not name a Program datatype"),
            Self::ProgramDatatypeParametersMustHaveTypeVtype => f.write_str("Program datatype parameters must have type \\VType"),
            Self::ProgramFieldProjectionExpectsARecordValue => f.write_str("Program field projection expects a record value"),
            Self::ProgramFunctionValuesRequireAnExplicitForceBeforeApplication => f.write_str("Program function values require an explicit \\force before application"),
            Self::ProgramRecordProjectionIsNotAComputation => f.write_str("Program record projection is not a computation"),
            Self::ProgramSyntaxCannotBeElaboratedAsASetPropExpression => f.write_str("Program syntax cannot be elaborated as a Set/Prop expression"),
            Self::ProgramTypeModuleParametersDoNotAcceptParameters => f.write_str("Program type module parameters do not accept parameters"),
            Self::ProgramTypeVariableUsedAsAValue => f.write_str("Program type variable used as a value"),
            Self::ProgramTypeVariableUsedAsAnApplicationHead => f.write_str("Program type variable used as an application head"),
            Self::ProgramTypeVariablesDoNotAcceptParameters => f.write_str("Program type variables do not accept parameters"),
            Self::ProgramValueRequiresReflection => f.write_str("Program value requires reflection"),
            Self::ProgramValueUsedAsAValueType => f.write_str("Program value used as a value type"),
            Self::ReflectedDefinitionCannotBeAppliedWithParameters => f.write_str("Reflected definition cannot be applied with parameters"),
            Self::SetReflectionRequiresAProgramDefinition => f.write_str("Set reflection requires a Program definition"),
            Self::TokenMatchEscapedTemplateExpansion => f.write_str("Token match escaped template expansion"),
            Self::VtypeIsOnlyValidInAProgramBinder => f.write_str("\\VType is only valid in a Program binder"),
            Self::TakeCurrentlyExpectsExactlyOneNamedVariable => f.write_str("\\take currently expects exactly one named variable"),
            Self::TakeMapMustHaveANonDependentCodomain => f.write_str("\\take map must have a non-dependent codomain"),
            Self::UnsupportedTakeProofBinder => f.write_str("\\take with proof bind is not supported by kernel TakeProp(X,P,f)"),
            Self::AlreadyAtRootModule => f.write_str("already at root module"),
            Self::AssociatedProgramItemHasTheWrongCategory => f.write_str("associated Program item has the wrong category"),
            Self::AssociatedItemIsNotAProgramComputation => f.write_str("associated item is not a Program computation"),
            Self::AssociatedItemIsNotAProgramDefinition => f.write_str("associated item is not a Program definition"),
            Self::AssociatedItemIsNotAProgramValue => f.write_str("associated item is not a Program value"),
            Self::BoundVariableOutsideSupportedContext => f.write_str("bound variable outside supported context"),
            Self::ProgramFunctionTypeNeedsAnnotation => f.write_str("cannot determine the type of Program function value; add a type annotation"),
            Self::CannotInferSquashTypeArgumentIsNotBoxedProgramCode => f.write_str("cannot infer \\squash type: argument is not boxed Program code"),
            Self::CheckpointSourceMissingFromProject => f.write_str("checkpoint source missing from project"),
            Self::ChildModuleInDeclarationExecutionOrder => f.write_str("child module in declaration execution order"),
            Self::CyclicDefinitionDependency => f.write_str("cyclic definition dependency"),
            Self::CyclicModuleParameterType => f.write_str("cyclic module parameter type"),
            Self::DefinitionIsNotAProgramComputation => f.write_str("definition is not a Program computation"),
            Self::DefinitionIsNotAProgramValue => f.write_str("definition is not a Program value"),
            Self::DefinitionLocalContextIsOutsideReferenceScope => f.write_str("definition local context is outside reference scope"),
            Self::DuplicateProgramAssociatedItemParameter => f.write_str("duplicate Program associated item parameter"),
            Self::ExpectedProgramStructureTypeInRecordLiteral => f.write_str("expected Program structure type in record literal"),
            Self::ExpectedProgramTypeBeforeAssociatedAccess => f.write_str("expected Program type before associated access"),
            Self::ExpectedProgramTypeBeforeAssociatedApplication => f.write_str("expected Program type before associated application"),
            Self::ExpectedASetPropSort => f.write_str("expected a Set/Prop sort"),
            Self::ExpectedADefinitionReference => f.write_str("expected a definition reference"),
            Self::ExpectedASort => f.write_str("expected a sort"),
            Self::ExpectedAStructureDataType => f.write_str("expected a structure data type"),
            Self::ExpectedAStructureTypeInAStructureLiteral => f.write_str("expected a structure type in a structure literal"),
            Self::ExpectedInductionBinders => f.write_str("expected induction binders"),
            Self::ExpectedModuleParameter => f.write_str("expected module parameter"),
            Self::ExpressionDoesNotHaveASort => f.write_str("expression does not have a sort"),
            Self::FailedToInferAProductTypeForTakeMap => f.write_str("failed to infer a product type for \\take map"),
            Self::IncorrectProgramTypeSort => f.write_str("incorrect Program type sort"),
            Self::MissingDefinitionCaptures => f.write_str("missing definition captures"),
            Self::NameDoesNotDenoteAProgramComputation => f.write_str("name does not denote a Program computation"),
            Self::OnlyProgramDatatypesAcceptTypeParameters => f.write_str("only Program datatypes accept type parameters"),
            Self::OnlyProgramParametersSupportSetReflection => f.write_str("only Program parameters support Set reflection"),
            Self::RecordConstructorHasTooFewFields => f.write_str("record constructor has too few fields"),
            Self::RecordFieldIndexOutOfBounds => f.write_str("record field index out of bounds"),
            Self::RecordFieldsMustBeNonRecursive => f.write_str("record fields must be non-recursive"),
            Self::ReflectionRequiresAProgramDefinition => f.write_str("reflection requires a Program definition"),
            Self::SourceDefinitionWasNotResolved => f.write_str("source definition was not resolved"),
            Self::UnexpandedMacroInHir => f.write_str("unexpanded macro in HIR"),
            Self::UnknownHirModule => f.write_str("unknown HIR module"),
            Self::UnknownHirModuleInExecutionOrder => f.write_str("unknown HIR module in execution order"),
            Self::UnknownHirParameter => f.write_str("unknown HIR parameter"),
            Self::UnknownDeclarationInExecutionOrder => f.write_str("unknown declaration in execution order"),
            Self::UnknownDefinition => f.write_str("unknown definition"),
            Self::UnknownModuleExpressionScope => f.write_str("unknown module expression scope"),
            Self::UnknownModuleParameter => f.write_str("unknown module parameter"),
            Self::UnresolvedDefinitionReflection => f.write_str("unresolved definition reflection"),
            Self::UnresolvedFrontendDeclaration => f.write_str("unresolved frontend declaration"),
            Self::UnresolvedFrontendValueDeclaration => f.write_str("unresolved frontend value declaration"),
            Self::UnresolvedReflectionMetavariable => f.write_str("unresolved reflection metavariable"),
            Self::UnresolvedStructureMember => f.write_str("unresolved structure member"),

        }
    }
}
