[package]
name = "elaboration"
version = "0.1.0"
edition = "2024"

[dependencies]
diagnostics.workspace = true
timing.workspace = true
miniz_oxide = "0.8.9"
postcard = { version = "1.1.3", default-features = false, features = ["alloc"] }
serde = { version = "1.0.229", features = ["derive", "rc"] }
kernel = { path = "../kernel" }
syntax = { path = "../syntax" }
resolve = { path = "../resolve" }
rustc-hash.workspace = true
smallvec = "1.15.1"
tracing = "0.1"


[lints.clippy]
too_many_arguments = "allow"
