//! Kernel expressions and their append-only arena.

use std::cell::RefCell;

use crate::ids::{DefId, InductiveId, MetaVarId, ModuleParamId, ProgramInductiveId, SymbolId};
use crate::sort::Sort;
use serde::{Deserialize, Serialize};

/// A stable index into an [`Arena`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct NodeId(u32);

impl NodeId {
    pub fn index(self) -> usize {
        self.0 as usize
    }
}

/// A handle to raw kernel syntax.
///
/// The elaborator's unclassified handle. Kernel judgement APIs classify this
/// as either [`Exp`] or [`crate::program::Program`].
pub type RawExp = NodeId;

/// A Set/Prop expression accepted by a Set/Prop judgement.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Exp(NodeId);

impl Exp {
    pub(crate) fn checked(raw: RawExp) -> Self {
        Self(raw)
    }

    pub fn raw(self) -> RawExp {
        self.0
    }
}

/// A successful Set/Prop typing judgement (`Gamma |- t : T`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
pub struct ExpJudgement {
    pub term: Exp,
    pub ty: Exp,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ProgramCaseBranch {
    pub binders: Vec<SymbolId>,
    pub body: RawExp,
}

/// A proof obligation attached to a checked Set/Prop expression is not part of
/// the calculus' computational syntax.  The front-end supplies witnesses for
/// these obligations and the kernel records them separately.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ProofObligation {
    pub context: Context,
    pub proposition: RawExp,
    pub rule: &'static str,
}

/// A user supplied witness for a provability judgement.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ProofEvidence {
    pub context: Context,
    pub proposition: RawExp,
    pub witness: RawExp,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub enum RawNode {
    Sort(Sort),
    ValueType,
    /// A locally bound variable, counted outwards from the occurrence.
    /// `Bound(0)` refers to the nearest enclosing binder.
    Bound(usize),
    /// A parameter of a module. Locally bound variables use [`RawNode::Bound`].
    ModuleParam(ModuleParamId),
    /// The Set-side variable produced by reflecting a Program module
    /// parameter.  This is generated by the meta-level reflection map and is
    /// never accepted in Program syntax.
    ReflectedProgramParam(ModuleParamId),
    /// An elaboration-time contextual metavariable applied to the variables
    /// in its declaration context.  A strict kernel check always rejects this
    /// node; the front-end must replace it before publishing a declaration.
    Meta {
        metavariable: MetaVarId,
        spine: Vec<RawExp>,
    },
    // A reference to a defined constant. The definition is stored in the environment.
    DefinedConstant(DefId),
    // (var: ty) -> body where var is bound in body but not in ty
    Prod {
        var: SymbolId,
        ty: RawExp,
        body: RawExp, // bind one variable
    },
    // (var: ty) => body where var is bound in body but not in ty
    Lam {
        var: SymbolId,
        ty: RawExp,
        body: RawExp, // bind one variable
    },
    // usual application (f x)
    App {
        func: RawExp,
        arg: RawExp,
    },
    IndType {
        indspec: InductiveId,
        parameters: Vec<RawExp>, // uncurry with parameter
    },
    IndCtor {
        indspec: InductiveId,
        parameters: Vec<RawExp>, // uncurry with parameter
        idx: usize,
    },
    IndElim {
        // this is primitive recursion
        indspec: InductiveId,
        elim: RawExp,
        return_type: RawExp,
        cases: Vec<RawExp>, // no bindings
    },
    /// Primitive projection for a one-constructor PTS structure.
    IndProjection {
        indspec: InductiveId,
        parameters: Vec<RawExp>,
        value: RawExp,
        field: usize,
    },
    /// Non-dependent Set case generated for the reflection of a Program
    /// datatype case.  The declaration environment determines branch field
    /// types and the corresponding reflected constructors.
    ReflectedProgramCase {
        indspec: ProgramInductiveId,
        scrutinee: RawExp,
        branches: Vec<ProgramCaseBranch>,
    },
    ThunkType {
        computation_ty: RawExp,
    },
    ReturnType {
        value_ty: RawExp,
    },
    ComputationFunction {
        domain: RawExp,
        codomain: RawExp,
    },
    RunStep {
        state_ty: RawExp,
        result_ty: RawExp,
    },
    ProgramIndType {
        indspec: ProgramInductiveId,
        parameters: Vec<RawExp>,
    },
    Thunk {
        computation: RawExp,
    },
    Continue {
        state_ty: RawExp,
        result_ty: RawExp,
        next: RawExp,
    },
    Finish {
        state_ty: RawExp,
        result_ty: RawExp,
        output: RawExp,
    },
    ProgramIndCtor {
        indspec: ProgramInductiveId,
        parameters: Vec<RawExp>,
        idx: usize,
        fields: Vec<RawExp>,
    },
    ProgramIndProjection {
        indspec: ProgramInductiveId,
        parameters: Vec<RawExp>,
        value: RawExp,
        field: usize,
    },
    Return {
        value: RawExp,
    },
    Force {
        value: RawExp,
    },
    ComputationLam {
        var: SymbolId,
        value_ty: RawExp,
        body: RawExp,
    },
    ComputationApp {
        computation: RawExp,
        value: RawExp,
    },
    Sequence {
        computation: RawExp,
        var: SymbolId,
        value_ty: RawExp,
        body: RawExp,
    },
    ValueLet {
        var: SymbolId,
        value: RawExp,
        body: RawExp,
    },
    ProgramCase {
        indspec: ProgramInductiveId,
        scrutinee: RawExp,
        branches: Vec<ProgramCaseBranch>,
    },
    Run {
        state_ty: RawExp,
        result_ty: RawExp,
        step: RawExp,
        initial: RawExp,
    },
    RunCase {
        state_ty: RawExp,
        result_ty: RawExp,
        step: RawExp,
        initial: RawExp,
        transition: RawExp,
    },
    // --- Set/Prop and Program connection -----------------------------------
    /// `Proof P`.  A [`ProofEvidence`] entry must discharge the corresponding
    /// provability premise before this node is accepted by the kernel.
    Proof {
        proposition: RawExp,
    },
    Acc {
        state_ty: RawExp,
        result_ty: RawExp,
        step: RawExp,
        state: RawExp,
    },
    RunStepRec {
        state_ty: RawExp,
        result_ty: RawExp,
        motive: RawExp,
        on_continue: RawExp,
        on_finish: RawExp,
        scrutinee: RawExp,
    },
    SetRun {
        state_ty: RawExp,
        result_ty: RawExp,
        step: RawExp,
        initial: RawExp,
    },
    SetRunCase {
        state_ty: RawExp,
        result_ty: RawExp,
        step: RawExp,
        initial: RawExp,
        transition: RawExp,
    },
    BoxType {
        program_ty: RawExp,
    },
    BoxProgram {
        program_ty: RawExp,
        program: RawExp,
    },
    ForceBox {
        program_ty: RawExp,
        boxed: RawExp,
    },
    BoxApp {
        function: RawExp,
        argument: RawExp,
    },
    /// Legacy implementation nodes retained only so old serialized/debug
    /// values receive a precise error.  New code uses `reflection`'s
    /// meta-level maps and the surface parser no longer constructs these.
    RfType {
        compute_ty: RawExp,
    },
    RfTerm {
        compute_ty: RawExp,
        term: RawExp,
    },
    AccIntro {
        state_ty: RawExp,
        result_ty: RawExp,
        step: RawExp,
        state: RawExp,
        predecessors: RawExp,
    },
    AccDescent {
        state_ty: RawExp,
        result_ty: RawExp,
        step: RawExp,
        from: RawExp,
        to: RawExp,
        accessibility: RawExp,
        transition: RawExp,
    },
    PowerSet {
        set: RawExp,
    },
    // {var: set | predicate} where var is bound in predicate but not in A
    SubSet {
        var: SymbolId,
        set: RawExp,
        predicate: RawExp,
    },
    Pred {
        superset: RawExp,
        subset: RawExp,
        element: RawExp,
    },
    TypeLift {
        superset: RawExp,
        subset: RawExp,
    },
    // Introduce `element` into `subset` of `superset` using `proof`.
    // This is a typing annotation and erases to `element` computationally.
    SubsetIntro {
        superset: RawExp,
        subset: RawExp,
        element: RawExp,
        proof: RawExp,
    },
    Equal {
        left: RawExp,
        right: RawExp,
    },
    // just non-emptyness proposition
    Exists {
        set: RawExp,
    },
    TakeSet {
        domain: RawExp,
        codomain: RawExp,
        map: RawExp,
        existence: RawExp,
        uniqueness: RawExp,
    },
    TakeProp {
        domain: RawExp,
        proposition: RawExp,
        map: RawExp,
        existence: RawExp,
    },
    ExistsIntro {
        element: RawExp,
        set: RawExp,
    },
    SubsetElim {
        element: RawExp,
        subset: RawExp,
        superset: RawExp,
    },
    IdRefl {
        element: RawExp,
    },
    IdElim {
        left: RawExp,
        right: RawExp,
        ty: RawExp,
        var: SymbolId,
        predicate: RawExp,
        base: RawExp,
        equality: RawExp,
    },
    AxiomSetExt {
        left: RawExp,
        right: RawExp,
        left_to_right: RawExp,
        right_to_left: RawExp,
    },
    AxiomFunExt {
        left: RawExp,
        right: RawExp,
        pointwise: RawExp,
    },
    AxiomClassicalIndefiniteChoice {
        domain: RawExp,
        family: RawExp,
        inhabited: RawExp,
    },
    TakeEq {
        func: RawExp,
        domain: RawExp,
        codomain: RawExp,
        element: RawExp,
        existence: RawExp,
        uniqueness: RawExp,
    },
}

#[cfg(feature = "bench-internals")]
#[derive(Debug, Clone, Copy)]
pub struct ArenaMark {
    nodes: usize,
}

/// Append-only storage for every kernel expression node.
#[derive(Debug, Default)]
pub struct Arena {
    nodes: RefCell<Vec<RawNode>>,
}

impl Arena {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn alloc(&self, node: RawNode) -> RawExp {
        let mut nodes = self.nodes.borrow_mut();
        let index = u32::try_from(nodes.len()).expect("expression arena exceeded u32::MAX");
        nodes.push(node);
        NodeId(index)
    }

    /// Return a shallow copy. Child expressions remain cheap `NodeId`s.
    pub fn get(&self, id: RawExp) -> RawNode {
        self.nodes.borrow()[id.index()].clone()
    }

    pub fn len(&self) -> usize {
        self.nodes.borrow().len()
    }

    pub fn is_empty(&self) -> bool {
        self.nodes.borrow().is_empty()
    }

    /// Checkpoint the arena for benchmark iteration cleanup.
    ///
    /// This is deliberately unavailable unless the `bench-internals` feature
    /// is enabled. Every expression allocated after the returned mark becomes
    /// invalid after [`Arena::rewind`].
    #[cfg(feature = "bench-internals")]
    pub fn mark(&self) -> ArenaMark {
        ArenaMark { nodes: self.len() }
    }

    /// Discard benchmark temporaries allocated after `mark`.
    ///
    /// Callers must not retain any expression allocated after the mark.
    #[cfg(feature = "bench-internals")]
    pub fn rewind(&self, mark: ArenaMark) {
        self.nodes.borrow_mut().truncate(mark.nodes);
    }

    pub fn sort(&self, sort: Sort) -> RawExp {
        self.alloc(RawNode::Sort(sort))
    }

    pub fn bound(&self, index: usize) -> RawExp {
        self.alloc(RawNode::Bound(index))
    }

    pub fn module_param(&self, parameter: ModuleParamId) -> RawExp {
        self.alloc(RawNode::ModuleParam(parameter))
    }

    pub fn as_module_param(&self, exp: RawExp) -> Option<ModuleParamId> {
        match self.get(exp) {
            RawNode::ModuleParam(parameter) => Some(parameter),
            _ => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub enum ContextEntry {
    Pts { var: SymbolId, ty: RawExp },
    ProgramType { var: SymbolId },
    ProgramValue { var: SymbolId, ty: RawExp },
}

impl ContextEntry {
    pub fn var(&self) -> SymbolId {
        match self {
            Self::Pts { var, .. } | Self::ProgramType { var } | Self::ProgramValue { var, .. } => {
                *var
            }
        }
    }
}

pub type Context = Vec<ContextEntry>;

/// An assumption in a Set/Prop context (`Gamma` in `system.md`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ExpContextEntry {
    pub var: SymbolId,
    pub ty: Exp,
}

pub type ExpContext = Vec<ExpContextEntry>;
