[package]
name = "front"
version = "0.1.0"
edition = "2024"

[dependencies]
either = "1.13.0"
lalrpop-util = { version = "0.21.0", features = ["lexer", "unicode"] }

[build-dependencies]
lalrpop = "0.22.2" 
