[book]
authors = ["pdf-jube-joba"]
language = "en"
src = "src"
title = "book"

[build]
build-dir = "out"
create-missing = false
use-default-preprocessors = false

[preprocessor.katex]
macros = "macros.txt"
